channels:
    - conda-forge    

dependencies:              
    - appmode
    - pandas
    - numpy
    - IPython
    - astropy==3.2.1
    - python
    - pip
    - pip:
            - pyvo
            - cadcutils
            - cadctap
            - git+https://github.com/glue-viz/glue-jupyter.git
            - ipyvuetify
            - ipywidgets
            - astroquery==0.3.10
            - drawSvg  
            - flake8
            - networkx
            - pycookiecheat
            - browser_cookie3
            - requests
